
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heart-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: heart-api
  template:
    metadata:
      labels:
        app: heart-api
    spec:
      containers:
      - name: heart-api
        image: heart-api:latest # replace with ghcr.io/<org>/<repo>:<tag> for public registry
        imagePullPolicy: Never   # use Always when pulling from remote registry
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: heart-api-svc
spec:
  type: NodePort
  selector:
    app: heart-api
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 30080
